//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lens
    {
        public int ID { get; set; }
        public int SectionID { get; set; }
        public string SPH { get; set; }
        public string CYL { get; set; }
        public string AXE { get; set; }
        public int Count { get; set; }
        public int Price { get; set; }
        public string Description { get; set; }
    
        public virtual Section Section { get; set; }
    }
}
